### PR TITLE
MySql storage support

### PR DESCRIPTION
**Pull request by rajan-goswami**
This commit adds support of MySql as rbac storage.

Notes on Test:
Please pre-create mysql database 'rbac' to run the tests on development machine

rbac-test

### CODE REVIEW

**Comment by rajan-goswami** [comment]
Hello @seeden 
I have implementd MySql storage implementation, and added it for the testing flow as well. It passes test cases and travis checks. Please merge. 
Thanks

**Comment by seeden** [comment]
Hi @rajan-goswami. Thank you for this driver. I will release new version but I am on vacation in this moment.

**Comment by rajan-goswami** [comment]
Hello @seeden,

If you are back from vacation, can you please release new version. So that we can use this library from npm repo.
Thanks

**Comment by shasif20** [comment]
Hey @seeden 
Waiting for new release with mysql storage.
Thanks

**Comment by shasif20** [comment]
That would be great.

**Comment by KemXoi1802** [comment]
This project have supported mysql storage, please provide some sample about it ?

**Pull request merged**
